[package]
name = "wasm_gzip"
version = "0.1.0"
authors = ["Enok <416828041@qq.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.62"
flate2 = "1.0.14"
wee_alloc = { version = "0.4.5" }

[profile.release]
opt-level = 'z'
lto = true