name: ci

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Deno
        uses: denolib/setup-deno@master
        with:
          deno-version: 1.0.3

      - name: Test
        run: deno test ./test.ts
